sudo: required
dist: trusty
language: c
matrix:
  include:
  - os: osx
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
node_js:
- 6
install:
- npm install electron-builder@next
- npm install
- npm run dist
script:
- npm run dist
